site_name: Guice-persist-orient

# Meta tags (placed in header)
site_description: Guice integration for OrientDB
site_author: 'Vyacheslav Rusakov'
site_url: 'https://xvik.github.io/guice-persist-orient'

# Repository (add link to repository on each page)
repo_name: guice-persist-orient
repo_url: http://github.com/xvik/guice-persist-orient
edit_uri: edit/master/src/doc/docs/

#Copyright (shown at the footer)
copyright: 'Copyright &copy; 2014-2018 Vyacheslav Rusakov'

# Meterial theme
theme: 'material'
extra:
#  palette:
#    primary: 'indigo'
#    accent: 'indigo'

  social:
    - type: 'github'
      link: 'https://github.com/xvik'
    - type: 'twitter'
      link: 'https://twitter.com/vyarus'


# Google Analytics
#google_analytics:
#  - 'UA-111111111-1'
#  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - footnotes
  - meta
  - toc(permalink=true)
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences

pages:
  - Home: index.md
  - User guide:
      - Installation: guide/installation.md
  - About:
      - Compatibility: about/compatibility.md
      - Release notes: about/history.md
      - Support: about/support.md
      - License: about/license.md